---
- user:
    name: rsletten

- file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  loop:
    - rsletten

- copy:
    src: authorized_keys
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0600
  loop:
    - rsletten
